services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
    - wordpress
    - mariadb
    restart: always
    networks:
      inception:
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      inception:

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      inception:

networks:
  inception:

volumes:
  mariadb_data:
  wordpress_data:

